server:
  port: 8072
 
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/
      
 
spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
        routes:
        #route id opzionale
        - id: organization-service
        #URI di destinazione 
          uri: lb://organization-service
        #immetto il percorso (opzionale)
          predicates:
          - Path=/organization/**
        #filtri per modificare la richiesta o risposta prima o dopo aver inviato la rispostaa
          filters:
          - RewritePath=/organization/(?<path>.*), /$\{path}
        - id: licensing-service
          uri: lb://licensing-service
          predicates:
          - Path=/license/**
          filters:
          - RewritePath=/license/(?<path>.*), /$\{path}


       
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        
